### PR TITLE
[ethtool] Add ethtool patch to version 5.8 to support QSFP-DD cable parsing

### PR DESCRIPTION
**Pull request by shlomibitton**
Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

**- Why I did it**
Add ethtool patch to version 5.8 to support QSFP-DD cable parsing.

**- How I did it**
Compiled the ethtool from:
https://git.kernel.org/pub/scm/network/ethtool/ethtool.git/commit/?id=88ca347ef35acb16ec0a0107f55ab599ddb18f56
Added it to 'files' directory.
Changed the buiild_debian.sh script to copy the file instead of downloading it.

**- How to verify it**
Build the image with this commit.
try to parse a QSFP-DD cable with the tool - "ethtool -m sfp#"

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by keboliu** [comment]
ethtool also installed in pmon, need to handle pmon build also

**Comment by shlomibitton** [comment]
> ethtool also installed in pmon, need to handle pmon build also

@keboliu I have added it also.

**Comment by keboliu** [comment]
Is it possible to have only one copy of bin for both host and pmon?

**Comment by shlomibitton** [comment]
> Is it possible to have only one copy of bin for both host and pmon?

@keboliu Changed it into a symlink.

**Review by keboliu — APPROVED** [review]

**Pull request closed without merging**
